import { defineStore } from "pinia";

export const useInputStore = defineStore("input", {
    state: () => ({
        name :"",
        last_name:"",
        father_name:"",
        field_of_study:"",
        id_number:"",
        id_alphabet:"",
        id_number_int:"",
        national_code:"",
        issue_place:"",
        mother_name:"",
        birth_day:"",
        birth_month:"",
        birth_year:"",
        country:"ایرانی",
        city:"",
        postal_code:"",
        religion:"",
        body_status:"",
        left_handed:"",
        father_occupation: "",
        father_work_address: "",
        father_education: "",
        father_work_phone: "",
        father_id: "",
        father_issue_place: "",
        father_birth_day: "",
        father_birth_month: "",
        father_birth_year: "",
        father_insurance_code: "",
        father_national_code: "",
        mother_occupation: "",
        mother_work_address: "",
        mother_education: "",
        mother_work_phone: "",
        mother_id: "",
        mother_issue_place: "",
        mother_birth_day: "",
        mother_birth_month: "",
        mother_birth_year: "",
        mother_insurance_code: "",
        mother_national_code: "",address: "",
        home_phone: "",
        housing_status: "",
        father_phone: "",
        mother_phone: "",
        phone: "",
        emergency_phone: "",
        children_before: "",
        family_members: "",
        study_room: "",
        live_with: "",
        housing_situation: "",
        student_supervisor: "",
        supervisor_birth_day: "",
        supervisor_birth_month: "",
        supervisor_birth_year: "",
        email: "",
        height: "",
        weight: "",
        ability: "",

    }),
    actions: {
      setInputValue(inputName, value) {
        this[inputName] = value;
      },
    },
  });